### ISSUE TITLE
roadmap and/or production readiness?

### ISSUE THREAD

**Issue by JeffBeltran** [Kong/swrv#107]
I was actually looking to move a Vue 2 project to React since i loved working with SWR in my day job, quick google brought me here. Few questions around the roadmap and production readiness.

1. what is the plan for Vue 3 support? or is the plan to keep this Vue 2 + @vue/composition-api or a bit longer? I saw there was a "beta" branch but that seems weird since this is still not a 1.0 release
2. would you add this to a production app in it's current state?

Thanks for all the hard work, looking forward to pulling this into my future projects.

**Comment by darrenjennings** [comment]
1. vue 3 support is "beta" mainly because it's a bit of a labor of love to support it. We don't use Vue 3 at Kong yet, but FWIW the test suite runs across both composition-api and Vue 3. So while it is not field tested by us, there is some confidence when we make changes. Support for `@vue/composition-api` isn't going anywhere anytime soon. The thought behind 0.x for swrv + composition-api is that vercel/swr itself is still <1.x and `swrv` relies on a beta peerDep (`@vue/composition-api`). semver is a little hard sometimes... The thought behind the beta was just to have a tag in npm without creating a new package like swrv-vue3 or something. I imagine long-term Vue 3 will be mainstream enough that swrv will have a major release for Vue 3 and composition-api will live on in whatever major release it is in.
2. With respect to production readiness, we (Kong) are actively building several applications with `@vue/composition-api`/`swrv` (composition api is still in 1.x-beta). Therefore, we're pretty committed to this library being battle tested alongside all our applications.

Disclaimer: this is open source project, so "production readiness" is maybe subjective here since there is no (legally binding) obligation to fix bugs with any SLA. That being said, hopefully this helps you decide to use swrv, and I am personally proud to support it.

**Comment by JeffBeltran** [comment]
Hey Darren, thanks for the response, this is what i wanted to hear.

> The thought behind the beta was just to have a tag in npm without creating a new package like swrv-vue3 or something

Perfect, this is what i figured but wanted clarification

> we (Kong) are actively building several applications with @vue/composition-api/swrv 

This is what i was looking for, this paired with my tests should be enough "piece of mind" i need. 

All in all this is a perfect fit for what i was looking for, and makes it easy for me to upgrade to vue3 when i'm ready to deal with that. Thanks again for taking the time to write this up, looking forward to playing around with this.

Cheers!
