### ISSUE TITLE
Hydration and SSG issues

### ISSUE THREAD

**Issue by brandonpittman** [Kong/swrv#18]
.

**Comment by darrenjennings** [comment]
@brandonpittman I looked at `swr`'s implementation early on and it seems that since react does not have lifecycle hooks, the useSWR hook requires users to manually fetch data on the server in whatever way they want, then pass the resolved data to the initialData prop. However, in Vue, the composition api supports `onServerPrefetch`, which `swrv` takes advantage of and allows users to not have to change their client side code. We even added some specific nuxt code to take advantage of nuxt's hydration. If you are trying to prefill/warm the cache client side, you can call `mutate` directly.

mutate docs:
https://github.com/Kong/swrv#prefetching

Relevant test:
https://github.com/Kong/swrv/blob/master/tests/ssr.spec.ts#L36

Let me know if you see something not working as expected, happy to look at a codesandbox reproduction.

**Comment by brandonpittman** [comment]
I’m trying to pre-render html using swrv’s data hook in a Gridsome project, and then have swrv rehydrate on load. Using axios, the HTML gets pre-rendered, but then hydration errors occur.

**Comment by darrenjennings** [comment]
@brandonpittman I tested it in gridsome and it looks like the SSR is working but the hydration is resetting data (aka not hydrating). Not seeing any errors. @atinux before I dig into the issue, do you have any idea on how gridsome's hyrdration might differ from nuxt's?

**Comment by brandonpittman** [comment]
If I wrap the swrv code in an if statement that checks for process.isClient, it runs perfectly on the client side.

**Comment by darrenjennings** [comment]
@brandonpittman I see you closed this issue. Was the bug resolved with the latest version or are you closing because you were able to get around it? Want to make sure that there's not a real issue outstanding.

Relevant recent SSR pr's:
https://github.com/Kong/swrv/pull/36
https://github.com/Kong/swrv/pull/39

**Comment by blumgart** [comment]
@brandonpittman Is there a solution to this problem? Data does not load when loading page (in Gridsome)

**Comment by brandonpittman** [comment]
@blumgart I just want it to stop showing up in my Github issues list.
