### ISSUE TITLE
Infinite Pagination

### ISSUE THREAD

**Issue by blocka** [Kong/swrv#19]
How would you do infinite pagination? In other words, when a new result comes in, you add it to the cache instead of clobbering it.

**Comment by darrenjennings** [comment]
@blocka haven't had to do that, but I understand that `swr` actually has its own baked in component `useSWRPages`. In lieu of implementing a special component, you can accomplish this like so:

https://codesandbox.io/s/swrv-19-infinite-pagination-wxyvz

However, this means that if you browse away and then return, you revalidate every swrv instance across all pages inside the infinite pagination. I realize through this exercise that it might be desired to allow for the hook to have a feature where you could disable revalidation and only serve from cache. This way you could serve all the pages but then only revalidate the latest page. 🤔

**Comment by blocka** [comment]
In my particular use case, persisting the results between pages was not a requirement, so that would actually work for me.
What I wound up doing was setting a watch on data, and then adding the data to a local ref, and displaying that. The ref could obviously be made "global" if I wanted to persist that across pages.

I ran into a strange bug, which I didn't have time to look into, which was that if I came back (in my particular case, I'm not switching pages, but switching tabs) when the query invalidated, the watcher got called twice, which caused the results to doubled...my quick fix was to `uniqBy` the results based on ID.

Perhaps I will try your idea it seems a little cleaner.

To me the ideal API would be something like:

```
const { data, error, loadMore } = useSWRV(....)
```
where loadMore would load the next set (you would obviously have to instruct it how to do so, that part of the API I haven't thought through), update the cache accordingly.

As an aside, setting a watch was a bit...awkward:

```
const { data } = useSWRV(....)
```
the data variable is Ref<any> | undefined

```
watch(data)
```

that actually works, although typescript doesn't like it because the undefined...couldn't the type be `Ref<any | undefined>` for the same price?

an additional aside, (sorry to clobber this issue here): although the library says, TS ready, it ignores generic argument practically

```
const { data } = useSWRV<Data>(....)

type Data2 = typeof data // still Ref<any> | undefined instead of Ref<Data> | undefined
```

**Comment by darrenjennings** [comment]
thanks @blocka I've added a new issue to track these typing issues. Would accept a PR if you are interested in contributing!

> when the query invalidated, the watcher got called twice, which caused the results to doubled...my quick fix was to uniqBy the results based on ID
The watcher firing twice is expected since the `data` Ref will be set twice, once from cache (stale), and once after the revalidate. On fresh data, it will fire twice, but the first time its value will be `undefined` so you wouldn't end up with duplicated data.

Keeping this issue open to discuss a better "infinite pagination" strategy or at least have a good example in the examples dir or codesandbox. I like the idea of a conditional "shouldRevalidate" config that, when set to false, will basically turn any individual hook into a simple fetcher from cache. This would be powerful because it also means that users could pass a function that does logic like "isSlowNetwork speeds" or any other business logic that would want to reduce revalidation events.

**Comment by darrenjennings** [comment]
Updated the infinite pagination. Now that we have #49 we can detect if the user is on the latest page and only revalidate the latest page. Note: Assumes that "pages" will always increment and that only the latest page should revalidate. If you have pages that are inconsistent, then you might want to revalidate all pages. Closing since this is now possible in user land and is customizable.

**Comment by blocka** [comment]
For what it's worth: https://swr.vercel.app/docs/pagination?#use-swr-infinite

**Comment by darrenjennings** [comment]
@blocka thanks for the link! Saw this released, and definitely open to contributions since not sure we need it here at Kong at the moment. Filing tickets to have swrv parity where makes sense: https://github.com/Kong/swrv/issues/72
