### ISSUE TITLE
Function-based Keys bail Nuxt Hydration

### ISSUE THREAD

**Issue by kofh** [Kong/swrv#38]
When using functions as keys for `useSWRV`, nuxt fails to rehydrate with the cache. I believe this is because the function is not called (see [line 134](https://github.com/Kong/swrv/blob/master/src/use-swrv.ts#L134))

`useSWRV` uses `keyRef` and assumes that `keyRef` is a `ref`, despite the function check on [line 123](https://github.com/Kong/swrv/blob/master/src/use-swrv.ts#L123). 

In testing, I've been able to get this to work by re-checking if `keyRef` is a function and if so calling it, otherwise accessing `value` like such:

```javascript
const instanceState = nodeState[isRef(keyRef) ? keyRef.value : keyRef()]
``` 

However, I'm not sure if this would have any unintended side effects.

**Comment by darrenjennings** [comment]
yea looks like a bug, since if `keyRef` is initially a function, then we will attach it to the watcher without transforming it into a ref first (https://vue-composition-api-rfc.netlify.app/api.html#watch "watching a single source"), and then we update the `keyRef.value` to be the resolved value in the watcher callback. However, hyrdration has already occurred. I think it is safe to invoke it here as you are doing.

**Comment by darrenjennings** [comment]
@kofh give it a try now in v0.3.2

**Comment by kofh** [comment]
That did the trick! Thanks so much for your quick response!
