### ISSUE TITLE
Does swrv support glocal configuration?

### ISSUE THREAD

**Issue by charshin** [Kong/swrv#91]
Does swrv support glocal configuration?
https://swr.vercel.app/docs/global-configuration

**Comment by darrenjennings** [comment]
No but I've wanted to add this for a while. I'm not sure if it would have much benefit to use a component wrapper like swr does via react's context, so I think it is ok to have it be per-app via a plugin. Something like:

```ts
import Vue from 'vue'
import { SwrvPlugin } from 'swrv'

Vue.use(SwrvPlugin({
  ...swrvConfigOptions 
})
```

```ts
// SwrvPlugin
export default (swrvConfig) => {
  install: (app) => {
    app.provide('swrv-config', swrvConfig)
  }
}
```

And then use-swrv.ts code can `inject['swrv-config']`.

**Comment by charshin** [comment]
I think you won't be able to `react` to changes to global configuration using plugin approach, anyway I am not sure `swr` itself supports that either, I think I am good with static global configuration for now.

**Comment by oliverpool** [comment]
Instead of a global configuration, I just wrapped useSWRV, with my own config:

```js
import Axios from "axios";
import useSWRV from "swrv";
import { computed } from "@vue/composition-api";

export default function use(key, fetcher, options) {
  if (!fetcher) {
    fetcher = (url) => Axios(url).then((res) => res.data);
  }
  if (!options) {
    options = {};
  }
  if (!options.shouldRetryOnError) {
    options.shouldRetryOnError = false;
  }
  if (!options.revalidateOnFocus) {
    options.revalidateOnFocus = false;
  }
  const swr = useSWRV(key, fetcher, options);
  return {
    ...swr,
    isLoading: swr.isValidating,
    isLoaded: computed(() => swr.data.value !== undefined),
    reload: () => swr.mutate(),
  };
}
```

And then I import this wrapper instead of the original `useSWRV`. 

This trick should work for every usecase and allow for more flexibility than what could be implemented in `swrv`.

@charshin what would be your usecase?

**Comment by darrenjennings** [comment]
@oliverpool this is how we use it at @kong so I agree it is probably fits most use cases. We can reopen in the future if @charshin weighs in otherwise adding a section to the docs should at least help users. I imagine there is some use case where you have many many components and you don't want have to know about the global config hook `use`, they can just "useSwrv" and provide/inject can take care of the config. @oliverpool would you like to add a section to the readme?
